name: 🔗 GHA
on: [push, pull_request, merge_group, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  windows-build:
    name: 🏁 Windows x86_64
    uses: ./.github/workflows/windows_builds.yml
